### ISSUE TITLE
batterymqtt

### ISSUE THREAD

**Issue by caramot** [fwPunsher/batteryMqtt#3]
Hello, i appreciate you work , but i have a small query 
can you update you code to add username and password for MQTT server ?
Unfortunatly , i don't have enought skills to do that by myself
Thank you

**Comment by promoshowfan** [comment]
hello ,
thanks for your work but is it possible to have a tutorial for use with Home Assistant please ?
Thank you
Laurent

**Comment by fwPunsher** [comment]
HI, 
ill add the two parameters in the next days when i find the time for this.

In regards to home assistant, I cant help with a detailed tutorial since I am using openhab instead of home assistant.
But the general steps should be similiar.

1. Run this script  as explained in the readme (either standalone or as container)
2. Point it to the MQTT broker that Home Assistant uses as well (configure a topic of your choosing)
3. Ad the config to map the generic data that is published to the topic you set above.

**Comment by jon7119** [comment]
hello
`import os
import asyncio
import websockets
import json
import requests
from paho.mqtt import client as mqtt_client

# Function to fetch environment variables and raise error if not set
def get_env_variable(var_name):
    value = os.getenv(var_name)
    if not value:
        raise EnvironmentError(f"Environment variable {var_name} is required and not set.")
    return value

# Configuration
broker = get_env_variable('MQTT_BROKER')
port = int(os.getenv('MQTT_PORT', 1883))
topic = os.getenv('MQTT_TOPIC', 'battery/reportEquip')
ws_uri = "ws://baterway.com:9501/equip/info/"
token_url = "http://baterway.com/api/user/app/login"
heartbeat_interval = int(os.getenv('HEARTBEAT_INTERVAL', 60))
reconnect_delay = int(os.getenv('RECONNECT_DELAY', 60))
app_code = os.getenv('APP_CODE', 'ASGOFT')
login_name = get_env_variable('LOGIN_NAME')
password = get_env_variable('PASSWORD')
token_credentials = {
    "appCode": app_code,
    "loginName": login_name,
    "password": password
}
deviceId = get_env_variable('DEVICE_ID')

# Logging the variables
print(f"MQTT Broker: {broker}")
print(f"MQTT Port: {port}")
print(f"MQTT Topic: {topic}")
print(f"WebSocket URI: {ws_uri}")
print(f"Token URL: {token_url}")
print(f"Heartbeat Interval: {heartbeat_interval}")
print(f"Reconnect Delay: {reconnect_delay}")
print(f"App Code: {app_code}")
print(f"Login Name: {login_name}")
print(f"Password: {password}")
print(f"Token Credentials: {token_credentials}")
print(f"Device ID: {deviceId}")


# Authorization Token Fetch
def get_auth_token():
    headers = {'Content-Type': 'application/json'}
    response = requests.post(token_url, json=token_credentials, headers=headers)
    if response.status_code == 200:
        response_data = response.json()
        if response_data['code'] == 200:
            return response_data['data']['token']
        else:
            raise Exception(f"Failed to fetch token: {response_data['message']}")
    else:
        raise Exception(f"HTTP error during token fetch: Status {response.status_code}")


# MQTT Connection Setup
def connect_mqtt():
    client = mqtt_client.Client(mqtt_client.CallbackAPIVersion.VERSION1)
    client.connect(broker, port)
    return client


# Send Initial and Heartbeat Messages
async def send_initial_and_heartbeat_messages(ws):
    initial_message = json.dumps({"reportEquip": [deviceId]})
    heartbeat_message = json.dumps({"heartbeat": [deviceId]})
    while True:
        if ws.open:
            await ws.send(initial_message)
            print(f"Sent initial message: {initial_message}")
            await ws.send(heartbeat_message)
            print(f"Sent heartbeat message: {heartbeat_message}")
        else:
            print("WebSocket is closed. Attempting to reconnect...")
            break
        await asyncio.sleep(heartbeat_interval)


# Main WebSocket and MQTT loop
async def websocket_to_mqtt():
    client = connect_mqtt()
    client.loop_start()
    while True:
        try:
            token = get_auth_token()
            uri = ws_uri + token
            headers = {
                "Authorization": token,
                "content-type": "application/json",
                "User-Agent": "okhttp/3.12.11"
            }
            async with websockets.connect(uri, extra_headers=headers) as websocket:
                # Start the message sending and receiving in parallel
                consumer_task = asyncio.create_task(receive_messages(websocket, client))
                producer_task = asyncio.create_task(send_initial_and_heartbeat_messages(websocket))
                done, pending = await asyncio.wait(
                    [consumer_task, producer_task],
                    return_when=asyncio.FIRST_COMPLETED
                )
                # Handle task completion or cancellation
                for task in pending:
                    task.cancel()
        except Exception as e:
            print(f"Error: {e}. Reconnecting in {reconnect_delay} seconds...")
            await asyncio.sleep(reconnect_delay)


# Receive and handle messages from WebSocket
async def receive_messages(websocket, mqtt_client):
    try:
        while True:
            message = await websocket.recv()
            print(f"Received message: {message}")
            if "totalPv1power" in message:
                mqtt_client.publish(topic, message)
            else:
                print("Message does not contain 'totalPv1power', not publishing.")
    except websockets.exceptions.ConnectionClosed:
        print("WebSocket connection closed.")


# Running the asyncio main function
async def main():
    await websocket_to_mqtt()


asyncio.run(main())`

`docker run -d \
  -e MQTT_BROKER='192.168.1.2' \
  -e MQTT_PORT='1883' \
  -e MQTT_TOPIC='battery/reportEquip' \
  -e MQTT_USERNAME='your_mqtt_username' \
  -e MQTT_PASSWORD='your_mqtt_password' \
  -e DEVICE_ID='DEVICE ID FROM APP' \
  -e APP_CODE='ASGOFT' \
  -e LOGIN_NAME='test@example.com' \
  -e PASSWORD='YourPassword' \
  --name battery-mqtt-client battery-mqtt-client`

**Comment by jon7119** [comment]
Hello I modified the code a little to add user and password for the MQTT Broker

**Comment by caramot** [comment]
Hello  . I will test that tomorrow.
Thank you a lot

**Comment by fwPunsher** [comment]
Hi @jon7119 
Feel free to open a Pull request.

**Comment by jon7119** [comment]
Good evening no worries, it seems to walk on the other hand it puts me that Error: failed to fetch token: the account (account) was not found. Reconnecting in 60 seconds ...
While I am well connected in the application

**Comment by fwPunsher** [comment]
Hi,
usually you cant be logged in with both the app and the script at the same time. But in those cases it will only kick you out.
Maybe the brand of your battery store doesn't match. What specific product are you using? You might want to double check login name, password and app code.

Regards

**Comment by jon7119** [comment]
Hello ok, that's what I thought we couldn't have both connecting, I tried to disconnect but the same, I use a storcube as battery but apparently it's the same servers
________________________________
De : fwPunsher ***@***.***>
Envoyé : jeudi 6 février 2025 08:43
À : fwPunsher/batteryMqtt ***@***.***>
Cc : jon7119 ***@***.***>; Mention ***@***.***>
Objet : Re: [fwPunsher/batteryMqtt] batterymqtt (Issue #3)


Hi,
usually you cant be logged in with both the app and the script at the same time. But in those cases it will only kick you out.
Maybe the brand of your battery store doesn't match. What specific product are you using? You might want to double check login name, password and app code.

Regards

**Comment by fwPunsher** [comment]
Yes its probably the same server, but the app code has to match the brand. What did you set it to?

**Comment by jon7119** [comment]
I'm not sure what to change for it to work

**Comment by fwPunsher** [comment]
my best guess would be STORECUBE. To know for sure you need to packet capture the communication of the android app. I used PCAPDroid for that.

**Comment by fwPunsher** [comment]
There was already someone with a storecube variant https://github.com/fwPunsher/batteryMqtt/issues/1

**Comment by jon7119** [comment]
/home/jon/batteryMqtt-main/batteryMqtt.py:50: DeprecationWarning: Callback API version 1 is deprecated, update to latest version
  client = mqtt_client.Client()  # Utilise la dernière version API MQTT
Error: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'. Reconnecting in 60 seconds...

**Comment by jon7119** [comment]
> There was already someone with a storecube variant [#1](https://github.com/fwPunsher/batteryMqtt/issues/1) thanks

**Comment by fwPunsher** [comment]
> /home/jon/batteryMqtt-main/batteryMqtt.py:50: DeprecationWarning: Callback API version 1 is deprecated, update to latest version client = mqtt_client.Client() # Utilise la dernière version API MQTT Error: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'. Reconnecting in 60 seconds...

Is that with our without the changes you made to the headers?

**Comment by jon7119** [comment]
with

**Comment by fwPunsher** [comment]
Had a quick look. It appears that the parameter was renamed to additional_headers in the library

**Comment by jon7119** [comment]
Who means?

**Comment by fwPunsher** [comment]
I have added a requirements.txt to enforce a version of the libraries thats known to be working. Please update your local code and try again

**Comment by jon7119** [comment]
thank you it works

**Comment by jon7119** [comment]
On the other hand in the MQTT the battery is not automatically detected but it appears in MQTT Explorer

**Comment by fwPunsher** [comment]
Where do you want it to be detected? If you mean home assistant, then you probably have to configure it manually as it doesnt publish any autodiscovery information.

**Comment by jon7119** [comment]
Yes sorry I was talking about detection on Home Assistant

**Comment by fwPunsher** [comment]
Yes auto discovery is not part of the script. It directly takes whatever the cloud service returns and pushes it to mqtt. This way its more robust to future changes and could also support other type of equipment that uses this cloud service.

**Comment by jon7119** [comment]
ok good I try to do something to have all the data on ha

**Comment by jon7119** [comment]
Is it possible to make a branch just for storcube?

**Comment by fwPunsher** [comment]
What would you need a separate branch for? The only difference is that you have to run it with different value for the app-code parameter.

**Comment by jon7119** [comment]
Ok it will just have to add in the doc then, well I go slowly for ha I have almost finished a few little worries to settle

**Comment by caramot** [comment]
Hello, i used the home-assistant core , i installed the docker by the terminal way , but i not undestand the reason of that comment appear  `/usr/src/app/./batteryMqtt.py:50: DeprecationWarning: Callback API version 1 is deprecated, update to latest version
  client = mqtt_client.Client()  # Utilise la dernière version API MQTT
Error: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'. Reconnecting in 60 seconds...` 


In HA , The paho-mqtt version is Version: 2.1.0

Did you have an idea how to fix it?

see below my procedure to install the docker in HA:

wget https://github.com/fwPunsher/batteryMqtt/archive/refs/heads/main.zip
unzip main.zip
cd batteryMqtt-main
rm batteryMqtt.py
wget https://raw.githubusercontent.com/fwPunsher/batteryMqtt/4947c76fe3c8bce5351aefd643b323acce5448ef/batteryMqtt.py
docker build -t battery-mqtt-client .

docker run ....

docker logs -f battery-mqtt-client

**Comment by fwPunsher** [comment]
Hi,

the python variant that HA uses is not relevant since each docker container brings its own dependencies.
Do you have the requirements.txt file I added recently?

The error is caused by the webseockets library not the mqtt.

**Comment by caramot** [comment]
Hello, 

I confirm , of course i used the last requirement , and i checked the docker version is ok .
please see below the tools versions:
Name: websockets
Version: 14.2
Name: requests
Version: 2.32.3
Name: paho-mqtt
Version: 2.1.0

**Comment by caramot** [comment]
hello , i update the Docker file to write the tools version . and now .  i receive the DATA . Thank you

**Comment by caramot** [comment]
hello, 
please see below , the sensor code to interprate the result of MQTT data

```
mqtt:
  sensor:   
    - state_topic: "battery/reportEquip"
      name: "battery totalPv2power" 
      value_template: '{{ value_json["ID_NUMBER"].totalPv2power }}'
      json_attributes_topic: "topic"
      unit_of_measurement: 'W'

    - state_topic: "battery/reportEquip"
      name: "battery totalPv1power" 
      value_template: '{{ value_json["ID_NUMBER"].totalPv1power }}'
      json_attributes_topic: "topic"
      unit_of_measurement: 'W'

    - state_topic: "battery/reportEquip"
      name: "battery totalInvPower" 
      value_template: '{{ value_json["ID_NUMBER"].totalInvPower }}'
      json_attributes_topic: "topic"
      unit_of_measurement: 'W'

    - state_topic: "battery/reportEquip"
      name: "battery totalCapacity" 
      value_template: '{{ value_json["ID_NUMBER"].totalCapacity }}'
      json_attributes_topic: "topic"
      unit_of_measurement: 'W'

    - state_topic: "battery/reportEquip"
      name: "battery temp" 
      value_template: '{{ value_json["ID_NUMBER"].list[0].temp }}'
      json_attributes_topic: "topic"
      unit_of_measurement: '°C'

    - state_topic: "battery/reportEquip"
      name: "battery capa1" 
      value_template: '{{ value_json["ID_NUMBER"].list[0].capacity }}'
      json_attributes_topic: "topic"
      unit_of_measurement: 'W'
  
    - state_topic: "homeassistant/battery"
      name: "battery plugPower" 
      value_template: '{{ value_json["ID_NUMBER"].plugPower }}'
      json_attributes_topic: "topic"   
      unit_of_measurement: 'W'
```

**Comment by promoshowfan** [comment]
Hello, I am closely following your progress, I admit that it is beyond my technical means.
I hope this can lead to an HA integration that can be used by everyone.
thank you for what you do for the community :)

**Comment by promoshowfan** [comment]
hello @caramot 

were you able to integrate the battery information into HA please?

**Comment by jon7119** [comment]
![Image](https://github.com/user-attachments/assets/7b767d31-1bf6-4cdf-98b2-f87bca149c90)

**Comment by jon7119** [comment]
![Image](https://github.com/user-attachments/assets/09c56e03-dc7a-4bf9-b56d-a61c4e147689)

**Comment by promoshowfan** [comment]
Bonjour @jon7119  oh c'est top ça , tu aurais un tuto à me communiquer stp ?
Tu prévois de publier comme intégration afin que cela puisse servir au plus grand nombre ?
merci d'avance de ton retour

**Comment by jon7119** [comment]
ha tu es français, je suis entrain d'améliorer le script mais ça prends du temps j'ai déjà pas mal avancé, il ya beaucoup de bidouilles pour le moment pour que cela marche, le script tourne sur un raspberry à coté

Ha you are French, I am improving the script but it takes time I have already advanced a lot, there are a lot of hacks for the moment so that it works, the script runs on a Raspberry next door

**Comment by promoshowfan** [comment]
oui Français :) , c'est surtout la partie Docker qui m'interroge car je n'ai pas d'expérience à ce sujet .
J'ai mon Home Assistant qui est installé sous Proxmox donc j'imagine qu'il doit être possible d'installer Docker sous Proxmox pour faire ensuite via Mqtt le lien avec HA.
En tout cas le résultat que tu as obtenu est vraiment sympa , cela me faciliterait la gestion de mes 3 batteries Storcube que je trouve plutôt sympa hormis la partie logicielle assez fermée .

yes French :), it is especially the Docker part that concerns me because I have no experience on this subject.
I have my Home Assistant which is installed under Proxmox so I imagine that it must be possible to install Docker under Proxmox and then make the link with HA via Mqtt.
In any case the result you obtained is really nice, it would make it easier for me to manage my 3 Storcube batteries which I find rather nice apart from the rather closed software part.

**Comment by jon7119** [comment]
@fwPunsher  a bien aider à faire le script que j'ai par la suite adapté et modifier, j'ai encore du boulot je récupére bien les infos de la batterie, pour le moment j'arrive a changer la puissance de sortie de la batterie, et bientôt le seuil de décharge de la batterie mais ça me prends du temps, pour le moment pas d'intégration direct sur HA je n'y connais rien mais ça viendra par la suite je pense si je trouve une solution simple ou si quelqu'un veut aider sur le projet.
Je ne connais pas proxmox mais oui tu dois pouvoir installer docker dessus

https://github.com/jon7119/batteryMqtt/

@fwpunsher to help make the script that I then adapted and modify, I still have a job I recover the battery info well, for the moment I can change the outlet power of the battery , and soon the battery discharge threshold but it takes me time, for the moment no direct integration on ha I know nothing but it will come later I think if I find a simple solution or if anyone 'One wants to help on the project.
I don't know Proxmox but yes you must be able to install Docker on it

**Comment by promoshowfan** [comment]
Je vais me pencher sur l'installation de docker sous Proxmox .
Effectivement merci également à @fwPunsher d'avoir initié le projet .

I'm going to look into installing docker under Proxmox.
Indeed, thanks also to @fwPunsher for initiating the project.

**Comment by jon7119** [comment]
If necessary hesitate to contact me if you need

**Comment by jon7119** [comment]
![Image](https://github.com/user-attachments/assets/5d2db28b-b8da-4b05-8f9f-0b9d6a58adf9)

**Comment by caramot** [comment]
> hello [@caramot](https://github.com/caramot)
> 
> were you able to integrate the battery information into HA please?

Hello, Yes 
I used the terminal in HA , like "Advanced SSH & Web Terminal"
In the terminal , i get the data with that command
`wget https://github.com/fwPunsher/batteryMqtt/archive/refs/heads/main.zip`
Unzip the file
`unzip main.zip`
go in the folder
`cd batteryMqtt-main`

Before to compile the docker , you need to update the docker file to
```
# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir websockets==12.0 paho-mqtt==2.1.0 requests==2.32.3
```
i used vi
`vi Dockerfile`
to write the data , press to i
for quit the write process , press escape
for save press :qw

After that , you need to compile the docker
`docker build -t battery-mqtt-client .`

The docker is now installed , we just need to launch the docker with parameter , plese used the docker run
```
docker run -d \
........
```

In HA , we need to configure the sensor , i used that for 2 batterys , it's possible of you need to adapt following your installation 
```
mqtt:
  sensor:   
    - state_topic: "battery/reportEquip"
      name: "battery totalPv2power" 
      value_template: '{{ value_json["ID_NUMBER"].totalPv2power }}'
      json_attributes_topic: "topic"
      unit_of_measurement: 'W'

    - state_topic: "battery/reportEquip"
      name: "battery totalPv1power" 
      value_template: '{{ value_json["ID_NUMBER"].totalPv1power }}'
      json_attributes_topic: "topic"
      unit_of_measurement: 'W'

    - state_topic: "battery/reportEquip"
      name: "battery totalInvPower" 
      value_template: '{{ value_json["ID_NUMBER"].totalInvPower }}'
      json_attributes_topic: "topic"
      unit_of_measurement: 'W'

    - state_topic: "battery/reportEquip"
      name: "battery totalCapacity" 
      value_template: '{{ value_json["ID_NUMBER"].totalCapacity }}'
      json_attributes_topic: "topic"
      unit_of_measurement: 'W'

    - state_topic: "battery/reportEquip"
      name: "battery temp" 
      value_template: '{{ value_json["ID_NUMBER"].list[0].temp }}'
      json_attributes_topic: "topic"
      unit_of_measurement: '°C'

    - state_topic: "battery/reportEquip"
      name: "battery capa1" 
      value_template: '{{ value_json["ID_NUMBER"].list[0].capacity }}'
      json_attributes_topic: "topic"
      unit_of_measurement: 'W'
  
    - state_topic: "homeassistant/battery"
      name: "battery plugPower" 
      value_template: '{{ value_json["ID_NUMBER"].plugPower }}'
      json_attributes_topic: "topic"   
      unit_of_measurement: 'W'
```
Have a good day
